services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
     - 443:443
    depends_on:
      - wordpress
    volumes:
     - wp_volume:/var/www/wordpress
    networks:
      - inception_net
    env_file: .env
    restart: on-failure
    
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wp_volume:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception_net
    expose:
      - 9000
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - db_volume:/var/lib/mysql
    env_file: .env
    networks:
      - inception_net
    expose:
      - 3306
    restart: on-failure

networks:
  inception_net:
    name: inception_net
    driver: bridge

volumes:
  wp_volume:
    name: wp_volume
    driver: local
    driver_opts:
      device: /home/asolano-/data/wordpress
      o: bind
      type: none
  db_volume:
    name: db_volume
    driver: local
    driver_opts:
      device: /home/asolano-/data/mariadb
      o: bind
      type: none